set(Plugin-Name "Inova Rigid Registration Plugin")
set(Plugin-Version "0.1")
set(Plugin-Vendor "Inova DE GmbH")
set(Plugin-ContactAddress "http://www.inova-de.eu")
set(Require-Plugin org.mitk.gui.qt.common org.mitk.gui.qt.datamanager)
