set(Plugin-Name "Registration Comparison")
set(Plugin-Version "0.1")
set(Plugin-Vendor "Inova DE GmbH")
set(Plugin-ContactAddress "http://inova.de")
set(Require-Plugin org.mitk.gui.qt.common org.mitk.gui.qt.datamanager)
