set(Plugin-Name "Registration Algorithms")
set(Plugin-Version "0.2")
set(Plugin-Vendor "Inova DE GmbH")
set(Plugin-ContactAddress "http://inova-de.eu")
set(Require-Plugin org.mitk.gui.qt.common org.mitk.gui.qt.datamanager org.mitk.matchpoint.core.helper)
